---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :compile_threads: <%= ENV['NUMBER_OF_PROCESSORS'] %>
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: ../../../toolchain/ceedling
  :default_tasks:
    - release

:release_build:
  :output: charon.elf
  :use_assembly: TRUE

:environment:

:extension:
  :executable: .exe
  :assembly: .s

:paths:
  :source:
    - ../../Library/**
    - Src/**
    - Drivers/STM32F4xx_HAL_Driver/Src/**
  :include:
    - Inc/**
    - Drivers/STM32F4xx_HAL_Driver/Inc
    - Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
    - Drivers/CMSIS/Device/ST/STM32F4xx/Include
    - Drivers/CMSIS/Include

:files:
  :assembly:
    - startup_stm32f407xx.s

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :release:
    - STM32F407xx


:tools:
   :release_compiler:
      :executable: "C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update/bin/arm-none-eabi-gcc.exe"
      :name: "ARM Cross GCC"
      :arguments:
         - -mcpu=cortex-m4
         - -mthumb
         - -mfloat-abi=hard
         - -ffunction-sections
         - -fdata-sections
         - -Wall
         - -g3
         - -c
         - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
         - -I$: COLLECTION_PATHS_SOURCE_AND_INCLUDE
         - -o ${2}
         - ${1}
   :release_assembler:
      :executable: "C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update/bin/arm-none-eabi-gcc.exe"
      :name: "ARM Cross GCC"
      :arguments:
         -  -x assembler-with-cpp
         - -mcpu=cortex-m4
         - -mthumb
         - -mfloat-abi=hard
         - -ffunction-sections
         - -fdata-sections
         - -Wall
         - -g3
         - -c
         - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
         - -I$: COLLECTION_PATHS_SOURCE_AND_INCLUDE
         - -o ${2}
         - ${1}
   :release_linker:
      :executable: "C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update/bin/arm-none-eabi-gcc.exe"
      :name: "ARM Cross GCC"
      :arguments:
         - -mcpu=cortex-m4
         - -mthumb
         - -mfloat-abi=hard
         - -ffunction-sections
         - -fdata-sections
         - -Wall
         - -g3
         - -Xlinker --gc-sections
         - -Wl,-Map,"build/artifacts/release/charon.map"
         - -T STM32F407VGTx_FLASH.ld
         - -o ${2}
         - ${1}

...
