/**
 *  Sentinel Software GmbH
 *  Copyright (C) 2020 Florian Kaup
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/**
 * @addtogroup CharonUDS
 * @{
 * @addtogroup HSDI
 * @{
 * @file charon_interface_debug.h
 * This Interface Describes the Functions needed by CHARON UDS for
 * its debug output Requirements.
 * For production these functions can be stubbed, so no debug overhead
 * is generated by debug messages.
 * For development these functions can be routed to any kind of
 * serial interface or console output. CHARON expects a printf-like
 * behavior.
 *
 * $Id:  $
 * $URL:  $
 * @}
 * @}
 */
/*****************************************************************************/

#ifndef CHARON_INTERFACE_DEBUG_H_
#define CHARON_INTERFACE_DEBUG_H_

/* Includes ******************************************************************/

#include <stdio.h>

/* Constants *****************************************************************/

/* Macros ********************************************************************/

// Include order!
// this file must be first in include order for windows build, so these macros
// are used by gcc instead of ../../Library/HSDI/charon_interface_debug.h

#define CHARON_INFO(x, ...)         printf("[Charon] Info: " x "\n", ##__VA_ARGS__); \
                                    fflush(stdout)
#define CHARON_WARNING(x, ...)      printf("[Charon] Warning: " x "\n", ##__VA_ARGS__); \
                                    fflush(stdout)
#define CHARON_ERROR(x, ...)        printf("[Charon] Error: " x "\n", ##__VA_ARGS__);   \
                                    fflush(stdout)


/* Types *********************************************************************/

/* Interfaces ****************************************************************/


#endif /* CHARON_INTERFACE_DEBUG_H_ */

/*---************** (C) COPYRIGHT Sentinel Software GmbH *****END OF FILE*---*/
